### PR TITLE
added click action to iimage

### PR DESCRIPTION
**Pull request by manuelkrieger**

### CODE REVIEW

**Comment by dockleryxk** [comment]
Thank you for doing this. I will test it out as soon as I can. 

If I can ever help you or Semabit out by adding or changing something with this slideshow (within reason of course) please let me know!

**Comment by jaysaikia** [comment]
Any reason for not merging this. I would really like to use the click function to switch to fullscreen slideshow.

**Comment by dockleryxk** [comment]
@jaysaikia I've been putting it off. Available in v1.2.3

**Comment by jaysaikia** [comment]
Thanks man. Like the component. 👍

**Pull request merged**
