### PR TITLE
PR:feat(zoom & pan)

### PR DESCRIPTION
**Pull request by jaysaikia**
Submitting this PR for review.

features:
touch/pinch "**zoom**" implemented
mouse click drag/touch "**pan**" implemented

tweaks:
"**click**" action reworked
"**swipe**" action reworked
"**README**" updated

note:
"**enablePan**" will disable all "**click**" action as requested by @dockleryxk

### CODE REVIEW

**Comment by dockleryxk** [comment]
Awesome! I review later today

**Comment by dockleryxk** [comment]
@jaysaikia I've been sick the past few days so still haven't looked through this. Just wanted to update you

**Comment by jaysaikia** [comment]
no worries ... take your time ... feel better

**Comment by dockleryxk** [comment]
Looking good! I've gone ahead and merged it, now I just need to do some server-side rendering tests

**Comment by jaysaikia** [comment]
Excellent. Thanks.

**Pull request merged**
