### PR TITLE
fullscreen implementation on bindable input

### PR DESCRIPTION
**Pull request by jaysaikia**
Please review the PR for fullscreen implementation on the component. Check the exit arrow design.

If you are happy, merge it, 
If not, let me know what I can do.

### CODE REVIEW

**Comment by dockleryxk** [comment]
@jaysaikia thank you for this PR! I will try to review it soon, but I have to ship my laptop off to get the keyboard fixed so it may not be until next week.

**Comment by dockleryxk** [comment]
@jaysaikia got my laptop back, I will be reviewing this tonight. In the meantime, what do you think about an implementation more like this? Perhaps your implementation could be a fallback if fullscreen isn't supported. (I will just add it when merging)

Note: this is abridged so doesn't include any checks from ngOnDestroy, etc.

```typescript
...
get isFullscreen() {
    return this.document.fullscreenElement ||
      this.document.webkitFullscreenElement ||
      this.document.mozFullScreenElement ||
      this.document.msFullscreenElement;
  }

enterFullscreen() {
    if (this.container.nativeElement.requestFullscreen) {
      this.container.nativeElement.requestFullscreen();
    }
    else if (this.container.nativeElement.mozRequestFullScreen) {
      this.container.nativeElement.mozRequestFullScreen();
    }
    else if (this.container.nativeElement.webkitRequestFullscreen) {
      this.container.nativeElement.webkitRequestFullscreen();
    }
    else if (this.container.nativeElement.msRequestFullscreen) {
      this.container.nativeElement.msRequestFullscreen();
    }
  }

exitFullscreen() {
    if (this.document.exitFullscreen) {
      this.document.exitFullscreen();
    }
    else if (this.document.mozCancelFullScreen) {
      this.document.mozCancelFullScreen();
    }
    else if (this.document.webkitExitFullscreen) {
      this.document.webkitExitFullscreen();
    }
    else if (this.document.msExitFullscreen) {
      this.document.msExitFullscreen();
    }
  }
```

**Comment by jaysaikia** [comment]
@dockleryxk Thanks for merging this. Was busy last few days at work.

**Comment by dockleryxk** [comment]
@jaysaikia no problem. Still curious about your thoughts on using the browser fullscreen functionality

**Comment by jaysaikia** [comment]
@dockleryxk I think it is a straight forward implementation, but I believe not all browsers are compatible at the moment, esp iOS

**Pull request merged**
