### PR TITLE
README update, FS exit event, FS exit position fix

### PR DESCRIPTION
**Pull request by jaysaikia**
Updated README file with fullscreen information
Stopped event propagation on fullscreen exit button
Added new fullscreen exit event
Fullscreen exit button position is now fixed to view port rather than absolute to relative parent element

### CODE REVIEW

**Comment by jaysaikia** [comment]
@dockleryxk Did you get a chance to look at this ?
Would like to help with the zoom and pan feature as well ...

**Comment by dockleryxk** [comment]
@jaysaikia ahh this somehow slipped through the cracks! I will look at it by the end of the week! Thank you for this

**Comment by jaysaikia** [comment]
@dockleryxk Did you have time to go through this PR ?

**Comment by dockleryxk** [comment]
Thank you again for this, sorry it took so long to go over it @jaysaikia !

**Pull request merged**
