### PR TITLE
feat(slider clickable) : Added slider as clickable

### PR DESCRIPTION
**Pull request by ssatz**
@dockleryxk  : Thanks for the wonderful package. 
I have added slider as clickable. Please review it and let me know if you are okay. 
I have changed the `<div>` to `<a> `tag  for  SEO also am not sure about the property **initial**

### CODE REVIEW

**Comment by dockleryxk** [comment]
@ssatz Thank you for this great contribution! At first glance this looks good to me, but I will check thoroughly tonight.

Also, The initial property is not important to these changes.

**Comment by dockleryxk** [comment]
@ssatz update: I had to work late so I did not get to look at this yet. I'll have plenty of time this weekend though.

**Comment by ssatz** [comment]
@dockleryxk  :+1:   Also  need to add router module to support routerlink.

**Comment by dockleryxk** [comment]
@ssatz I have not forgotten about this! When I tried to merge a different PR it took up too much time to merge this. I have reverted that and will get to this asap.

**Comment by ssatz** [comment]
@dockleryxk : 👍  pls check #11  which will be easy for you to merge.

**Comment by dockleryxk** [comment]
@ssatz This is live as well as #11 in v1.15. Be aware that I removed the href from ISlide and only use it from IImage

**Pull request merged**
