### PR TITLE
feat(component) : add optional image caption

### PR DESCRIPTION
**Pull request by GusMonkeySoft**
Thank you for providing this module.

I did some changes to add image caption on bottom :
- Add new type IImage { url: string, caption?: string }
- Change ISlider.url: string to ISlider.image: IImage
- Change component.imageUrls: string[] to component.imageUrls: (string | IImage)[] (preserving compatibility)
- Add optional caption zone in slide zone view
- Change usage samples to show all cases

PR#7 (clickable image) changes can be added too.

### CODE REVIEW

**Comment by GusMonkeySoft** [comment]
Thank you for providing this module.

I did some changes to add image caption on bottom.
PR#7 (clickable image) changes can be added too.

**Comment by GusMonkeySoft** [comment]
Sorry for miss-click on close...

**Comment by dockleryxk** [comment]
Thank you for this awesome PR! I especially appreciate your attention to compatibility. I won't be able to merge this for a week or two as I am currently traveling. I will update you here if anything else changes, otherwise I will merge this asap!

**Comment by GusMonkeySoft** [comment]
This new commit add PR#7 idea from @ssatz to simplify integration of both.

**Comment by ssatz** [comment]
@GusMonkeySoft  : 👍 Thanks for making  compatibility with PR#7. 
thus making optional won't impact the updation of the package

**Comment by dockleryxk** [comment]
@GusMonkeySoft This is live in v1.15. Be aware that I removed the href from ISlide and only use it from IImage

**Comment by dockleryxk** [comment]
@juan2manny fixed in v1.1.8

**Pull request merged**
